const { test } = require('node:test');
const assert = require('node:assert/strict');
const { spawn } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const sharp = require('sharp');

test('account sessions, admin authorization, content and image validation', async (t) => {
  const data = fs.mkdtempSync(path.join(os.tmpdir(), 'dark-test-'));
  const child = spawn(process.execPath, ['src/server.js'], { env: { ...process.env, PORT: '3199', DATA_DIR: data, DB_PATH: path.join(data, 'dark-games.db'), UPLOADS_DIR: path.join(data, 'uploads'), JWT_SECRET: 'test-only-secret-not-for-production-12345', ADMIN_USERNAME: 'testadmin', ADMIN_PASSWORD: 'TestAdminPassword1', NODE_ENV: 'test', COOKIE_SECURE: 'false' }, stdio: ['ignore', 'pipe', 'pipe'] });
  t.after(async () => { child.kill(); await new Promise(r => child.exitCode !== null ? r() : child.once('exit', r)); fs.rmSync(data, { recursive: true, force: true }); });
  await new Promise((resolve, reject) => { const timer = setTimeout(() => reject(new Error('Server startup timeout')), 15000); child.stdout.on('data', b => { if (b.toString().includes('running on')) { clearTimeout(timer); resolve(); } }); child.once('exit', code => { clearTimeout(timer); reject(new Error(`Server exited ${code}`)); }); });
  const call = (url, method = 'GET', body, cookie) => fetch(`http://127.0.0.1:3199${url}`, { method, headers: { 'content-type': 'application/json', ...(cookie ? { cookie } : {}) }, body: body ? JSON.stringify(body) : undefined });
  const cookieOf = r => r.headers.get('set-cookie').split(';')[0];
  let r = await call('/api/auth/register', 'POST', { username: 'tester', password: 'OriginalPassword1' });
  assert.equal(r.status, 201); const original = cookieOf(r);
  assert.equal((await call('/api/admin/news', 'GET', null, original)).status, 403);
  r = await call('/api/profile/password', 'POST', { currentPassword: 'OriginalPassword1', newPassword: 'ChangedPassword2' }, original);
  assert.equal(r.status, 200); const changed = cookieOf(r);
  assert.equal((await call('/api/auth/me', 'GET', null, original)).status, 401);
  assert.equal((await call('/api/auth/me', 'GET', null, changed)).status, 200);
  assert.equal((await call('/api/profile/avatar', 'POST', { imageData: 'data:image/png;base64,bm90LWFuLWltYWdl' }, changed)).status, 400);
  const png = await sharp({ create: { width: 12, height: 12, channels: 3, background: '#7b98a3' } }).png().toBuffer();
  r = await call('/api/profile/avatar', 'POST', { imageData: `data:image/png;base64,${png.toString('base64')}` }, changed);
  assert.equal(r.status, 200); const profile = await r.json(); assert.match(profile.user.avatarUrl, /\.webp$/);
  assert.equal((await call(profile.user.avatarUrl)).status, 200);
  assert.equal((await call('/api/auth/logout-all', 'POST', {}, changed)).status, 200);
  assert.equal((await call('/api/auth/me', 'GET', null, changed)).status, 401);
  r = await call('/api/auth/login', 'POST', { username: 'testadmin', password: 'TestAdminPassword1' });
  assert.equal(r.status, 200); const admin = cookieOf(r);
  r = await call('/api/admin/news', 'POST', { title: 'Test published news', body: 'Persistent text', status: 'published' }, admin);
  assert.equal(r.status, 201); const news = await r.json();
  assert.equal((await (await call(`/api/content/news/${news.id}`)).json()).body, 'Persistent text');
  r = await call('/api/admin/lore/chapters', 'POST', { title: 'Город тестов', body: 'Место встречи игроков', category: 'cities', published: true }, admin);
  assert.equal(r.status, 201);
  assert.equal((await call('/api/unknown')).status, 404);
  assert.equal((await call('/missing-page')).status, 404);
  assert.equal((await call('/play')).status, 200);
});
